apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  type: {{ .Values.service.type }}
  selector:
    app: spark-master
  ports:
    - name: web
      port: 8080
      targetPort: 8080
    - name: spark
      port: 7077
      targetPort: 7077
